application: hazewatcher
version: alpha1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: .*
  static_files: templates/index.html
  upload: templates/index.html

libraries:
- name: webapp2
  version: latest